import type { Metadata } from "next";
import type { ReactNode } from "react";

import localFont from "next/font/local";
import "./globals.css";

type Props = {
  children: ReactNode;
};

const medieval = localFont({
  src: "./fonts/EnchantedLand.otf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Banca | S.O",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html>
      <body className={medieval.className}>{children}</body>
    </html>
  );
}
